### ISSUE TITLE
Multi-echo and uncombined name updaters assume lists instead of sets

### ISSUE THREAD

**Issue by tsalo** [nipy/heudiconv#460]
### Summary

When converting multi-echo data without an EchoNumber metadata field, `heudiconv.convert.update_multiecho_name()` attempts to index `echo_times`. The problem is that this parameter is a `set`, rather than a `list`, so doing this raises an error. The same should apply to `heudiconv.convert.update_uncombined_name()`.

Here is the traceback:
```python
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/home/code/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/home/code/heudiconv/heudiconv/main.py", line 344, in workflow
    grouping=grouping,)
  File "/home/code/heudiconv/heudiconv/convert.py", line 211, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/home/code/heudiconv/heudiconv/convert.py", line 459, in convert
    overwrite=overwrite)
  File "/home/code/heudiconv/heudiconv/convert.py", line 713, in save_converted_files
    bids_meta, this_prefix_basename, echo_times
  File "/home/code/heudiconv/heudiconv/convert.py", line 326, in update_multiecho_name
    echo_number = echo_times.index(metadata['EchoTime']) + 1
AttributeError: 'set' object has no attribute 'index'
```

This wasn't caught by the tests for these functions because I mistakenly used lists as the arguments in the tests.

EDIT: Introduced in #424, so at least it hasn't affected any releases.

### Platform details:

Choose one:
- [ ] Local environment

- [X] Container: Docker using current master (as of f4c2dd2).

- Heudiconv version: Current master (as of f4c2dd2).

**Comment by tsalo** [comment]
I think the simplest solution is to change the `echo_times` and `channel_names` variables in `heudiconv.convert.convert()` from sets to lists. @yarikoptic does that sound alright?

I could also add in type checks to the beginning of the name-updating functions, just to be extra safe.

**Comment by mckenziephagen** [comment]
Running into this exact issue, version `0.9.0` in a singularity container. Is the above PR going to be merged sometime soon, or am I better off making these changes myself in my singularity container? Thanks!

**Comment by tsalo** [comment]
I think it's ready, but I don't know if anyone has had a chance to review.

**Comment by tsalo** [comment]
@mckenziephagen If you have the time, it might be helpful if you could review #461?

**Comment by mckenziephagen** [comment]
Can do - what exactly does a review entail for this project?
